-- "" 表示字符串，不支持 ``
CREATE TABLE IF NOT EXISTS "flow" (
  "id" BIGINT PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "json_data" BLOB NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);