-- "" 表示字符串，不支持 ``
CREATE TABLE IF NOT EXISTS "flow" (
  "id" BIGINT PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "json_data" BLOB NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE IF NOT EXISTS "flow_his" (
  "id" BIGINT PRIMARY KEY,
  "flow_id" BIGINT NOT NULL,
  "json_data" BLOB NOT NULL,
  "start_at" TIMESTAMP NULL, -- 开始时间
  "end_at" TIMESTAMP NULL, -- 结束时间
  "exec_st" VARCHAR NOT NULL DEFAULT 'INIT', -- 执行状态: { INIT: 初始化, RUNNING: 执行中, SUCCESS: 成功, FAILED: 失败 }
  "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);